squashed commit with lots of feature fixes and new bugs.

diff --git a/sync_core b/sync_core
--- a/sync_core
+++ b/sync_core
@@ -1,7 +1,6 @@
 #!/bin/bash
 
-
-SERVERNAME=$(hostname --fqdn)
+SERVERNAME=$( hostname --fqdn ) # added a space before `)' to fix vim syntax highlighting issue
 
 function kvdb_global_get_file_name {
     DBF="$KVDBROOT/global.kc"
@@ -74,26 +73,31 @@ if [ ! -d "$LOGROOT/$1" ]; then
     mkdir -p "$LOGROOT/$1"
 fi
 
-for ((i=13;i>=0;i--)); do
+for ((i=13; i>=0; i--)); do
     j=$((i+1))
     mv "$LOGROOT/$1/log.stdout.$i" "$LOGROOT/$1/log.stdout.$j" 2>/dev/null
     mv "$LOGROOT/$1/log.stderr.$i" "$LOGROOT/$1/log.stderr.$j" 2>/dev/null
+    mv "$LOGROOT/$1/log.outerr.$i" "$LOGROOT/$1/log.outerr.$j" 2>/dev/null
 done
 mv "$LOGROOT/$1/log.stdout" "$LOGROOT/$1/log.stdout.0"
 mv "$LOGROOT/$1/log.stderr" "$LOGROOT/$1/log.stderr.0"
+mv "$LOGROOT/$1/log.outerr" "$LOGROOT/$1/log.outerr.0"
 
 
-date -u > "$MIRRORROOT/$1/Archive-Update-in-Progress-${SERVERNAME}"
+date -u > "$MIRRORROOT/$1/Archive-Update-in-Progress-${SERVERNAME}";
 
-if _sync >"$LOGROOT/$1/log.stdout" 2>"$LOGROOT/$1/log.stderr"; then
+set -e # Fail immediately if error occurs
+
+if _sync > >(tee -a "$LOGROOT/$1/log.outerr" > "$LOGROOT/$1/log.stdout" ) 2> >(tee -a "$LOGROOT/$1/log.outerr" > "$LOGROOT/$1/log.stderr"); then
     LASTSTATUS=success
     if [ -f "$MIRRORROOT/$1/Archive-Update-in-Progress-${SERVERNAME}" ]; then
-    	rm "$MIRRORROOT/$1/Archive-Update-in-Progress-${SERVERNAME}"
+        rm "$MIRRORROOT/$1/Archive-Update-in-Progress-${SERVERNAME}"
     fi
     SIZE=$(_get_size)
     NEXTSYNC=$(_get_next_sync_time)
     LASTSYNC=$(date +%s)
     python -c 'import json;from itertools import izip;import sys;i=iter(sys.argv[1:]);print json.dumps(dict(izip(i,i)))' upstream "$UPSTREAM" size "$SIZE" status success lastsync "$LASTSYNC" nextsync "$NEXTSYNC" name $1 > "$STATUSROOT/$1.json" 2>/dev/null
+    _post_sync > >(tee -a "$LOGROOT/$1/log.outerr" >> "$LOGROOT/$1/log.stdout" ) 2> >(tee -a "$LOGROOT/$1/log.outerr" >> "$LOGROOT/$1/log.stderr")
 else
     LASTSTATUS=failed
     if [ -f "$MIRRORROOT/$1/Archive-Update-in-Progress-${SERVERNAME}" ]; then
